name: Docker Build & Push

on:
  workflow_dispatch:
  push:
    branches:
      - latest-kubesphere

env:
  IMAGE_NAME: shell-operator
  IMAGE_REPO: lisy09kubesphere
  IMAGE_VERSION: latest-alpine3.12
  DOCKER_PLATFORMS: linux/amd64,linux/arm/v7,linux/arm64

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: "linux/amd64,linux/arm64,linux/arm/v7"

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Builder instance name
        run: echo ${{ steps.buildx.outputs.name }}

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Log into registry
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build and push image
        run: |
          IMAGE_ID=$IMAGE_REPO/$IMAGE_NAME
          echo IMAGE_ID=$IMAGE_ID

          docker buildx build \
            --push \
            --file Dockerfile-alpine3.12 \
            --tag $IMAGE_ID:$IMAGE_VERSION \
            --platform $DOCKER_PLATFORMS .
